#!/bin/sh
#
# Is dist/compilerpp_amalgamated.cpp still this compiler?
#
#   ./run_amalgamated.sh <path-to-Compiler++-binary> [host-c++]
#
# The amalgamation is generated but committed, and it was regenerated by hand.
# So it went stale -- twenty-two commits stale -- and nothing noticed, because
# nothing in any suite built it.  It still COMPILED, which is what made it
# dangerous: a file that builds looks current.  What it had become was a
# different compiler, missing new[]/delete[], cin, bool references and four
# maths natives, and shipping the copy semantics of three weeks earlier to
# anyone who built the single-file distribution.
#
# Two checks, and they fail for different reasons:
#
#   1. UP TO DATE.  Regenerate into a temporary file and compare.  This is the
#      one that catches rot, it needs nothing but python3, and it is exact.
#
#   2. THE SAME COMPILER.  Build the committed file and put every case through
#      both binaries.  Check 1 says the TEXT matches; only this says the
#      concatenation produced the same program.  An amalgamation is where a
#      file-scope name collides with another file's, and a diff cannot see it.

BIN="$1"
HOSTCXX="${2:-c++}"

if [ -z "$BIN" ] || [ ! -x "$BIN" ]; then
    echo "usage: $0 <path-to-Compiler++-binary> [host-c++]" >&2
    exit 2
fi
# The reference binary is compared against, so name it before the cd changes
# what a relative path means.
case "$BIN" in /*) ;; *) BIN="$PWD/$BIN" ;; esac

DIR=$(dirname "$0")
cd "$DIR/.." || exit 2          # the project root: amalgamate.py wants it

WORK=${TMPDIR:-/tmp}/cxxamalg.$$
mkdir -p "$WORK" || exit 2
trap 'rm -rf "$WORK"' EXIT

fail=0

# --- 1. is the committed file what the sources generate? --------------------

# Probed by RUNNING it, not by finding it.  Windows ships a python3 on PATH
# that is a Microsoft Store shortcut: `command -v` finds it, and executing it
# prints an advertisement and exits 49.  Looking would report the staleness
# check as failed on every Windows box, which is a lie about the amalgamation.
if python3 -c 'import sys; sys.exit(0)' >/dev/null 2>&1; then
    cp dist/compilerpp_amalgamated.cpp "$WORK/committed.cpp"
    if python3 dist/amalgamate.py > "$WORK/gen.log" 2>&1; then
        if diff -q "$WORK/committed.cpp" dist/compilerpp_amalgamated.cpp >/dev/null 2>&1; then
            echo "ok       up to date with Compiler++/"
        else
            echo "FAIL     dist/compilerpp_amalgamated.cpp is STALE"
            echo "         it does not match what Compiler++/ generates:"
            diff "$WORK/committed.cpp" dist/compilerpp_amalgamated.cpp | sed -n '1,12p'
            echo "         regenerate it:  python3 dist/amalgamate.py"
            fail=$((fail + 1))
        fi
        # Leave the working tree as it was found, whichever way that went: a
        # test that rewrites a committed file is not a test.
        cp "$WORK/committed.cpp" dist/compilerpp_amalgamated.cpp
    else
        echo "FAIL     dist/amalgamate.py did not run"
        sed -n '1,6p' "$WORK/gen.log"
        fail=$((fail + 1))
    fi
else
    echo "SKIP     staleness check (no working python3 to regenerate with)"
fi

# --- 2. does it build, and is it the same compiler? -------------------------

if ! command -v "$HOSTCXX" >/dev/null 2>&1; then
    echo "SKIP     build and comparison (no '$HOSTCXX' to build with)"
    echo
    echo "$([ "$fail" -eq 0 ] && echo "amalgamation checked" || echo "amalgamation FAILED")"
    [ "$fail" -eq 0 ]
    exit $?
fi

# MSVC is the audience this file was written for -- a machine with a compiler
# and no project file -- so it must be buildable by cl, which takes none of the
# flags above.  Its own /std has no c++98; CMakeLists says the same and for the
# same reason, MSVC's default being close enough and the source using nothing
# newer.
#
# The options are written with a DASH, not a slash.  cl has always accepted
# both, and the shell that runs this on Windows is Git bash, whose MSYS layer
# rewrites an argument beginning with '/' into a Windows path: `-nologo` as
# `/nologo` arrives at cl as `C:/Program Files/Git/nologo`, and `/Fe:x` as
# `...\Fe;x` -- five "unrecognized source file type" warnings and then a real
# error about the /EHsc that was eaten on the way in.  Dashes pass through.
#
# And cl is a NATIVE program, so the directory it is told to write into has to
# be named the way Windows names it.  Git bash's /tmp is not a path cl can
# resolve -- it reads it as C:\tmp and stops with "Cannot open compiler
# generated file".  cygpath, which ships with that shell, is what knows the
# difference; without it the POSIX name is passed through unchanged, which is
# correct everywhere cl is not involved.
AMALG="$WORK/amalg"
case "$(basename "$HOSTCXX")" in
    cl|cl.exe)
        AMALG="$WORK/amalg.exe"
        NATIVE_WORK="$WORK"
        if command -v cygpath >/dev/null 2>&1; then
            NATIVE_WORK=$(cygpath -m "$WORK")
        fi
        set -- -nologo -W4 -EHsc "-Fe:$NATIVE_WORK/amalg.exe" "-Fo:$NATIVE_WORK/" \
               dist/compilerpp_amalgamated.cpp
        ;;
    *)
        set -- -std=c++98 -Wall -Wextra -o "$AMALG" dist/compilerpp_amalgamated.cpp
        ;;
esac

if "$HOSTCXX" "$@" > "$WORK/build.log" 2>&1; then
    # Warnings matter here as much as errors: the per-file build is clean, so
    # anything the one-file build says is something concatenation introduced.
    # Matched by word rather than by an empty log, cl printing the file name it
    # is compiling whether or not it has anything to say about it.
    if grep -i -q 'warning' "$WORK/build.log"; then
        echo "FAIL     it builds, with warnings the per-file build does not give"
        grep -i 'warning' "$WORK/build.log" | sed -n '1,10p'
        fail=$((fail + 1))
    else
        echo "ok       builds clean as one translation unit"
    fi
else
    echo "FAIL     dist/compilerpp_amalgamated.cpp does not build"
    sed -n '1,10p' "$WORK/build.log"
    fail=$((fail + 1))
    echo
    echo "amalgamation FAILED"
    exit 1
fi

same=0
differ=0
for case_file in tests/cases/*.cpp; do
    name=$(basename "$case_file" .cpp)
    input=/dev/null
    [ -f "tests/input/$name.txt" ] && input="tests/input/$name.txt"

    "$BIN"        -ast -layout -ir -q "$case_file" > "$WORK/a.dump" 2>&1 </dev/null; astat=$?
    "$AMALG"      -ast -layout -ir -q "$case_file" > "$WORK/b.dump" 2>&1 </dev/null; bstat=$?

    "$BIN"        -run -q "$case_file" > "$WORK/a.run" 2>&1 < "$input"; arun=$?
    "$AMALG"      -run -q "$case_file" > "$WORK/b.run" 2>&1 < "$input"; brun=$?

    if [ "$astat" -eq "$bstat" ] && [ "$arun" -eq "$brun" ] &&
       diff -q "$WORK/a.dump" "$WORK/b.dump" >/dev/null 2>&1 &&
       diff -q "$WORK/a.run"  "$WORK/b.run"  >/dev/null 2>&1; then
        same=$((same + 1))
    else
        echo "DIFF     $name  (the one-file build answers differently)"
        diff -u "$WORK/a.dump" "$WORK/b.dump" 2>/dev/null | sed -n '3,10p'
        diff -u "$WORK/a.run"  "$WORK/b.run"  2>/dev/null | sed -n '3,10p'
        differ=$((differ + 1))
        fail=$((fail + 1))
    fi
done
echo "ok       $same cases answered identically$([ "$differ" -gt 0 ] && echo ", $differ did not")"

echo
if [ "$fail" -eq 0 ]; then
    echo "amalgamation is current, builds clean, and is the same compiler"
else
    echo "amalgamation FAILED $fail check(s)"
fi
[ "$fail" -eq 0 ]
