//
//  main.cpp
//  Compiler++
//
//  Created by G. R. Akhtar on 29/08/2026.
//
//  Reads a source file and runs it through the front end:
//      Parser -> Semantic -> Layout -> Lower, reporting via Diagnostics.
//
//  Usage:   Compiler++ [options] [source-file]
//             -ast        print the syntax tree
//             -layout     print each class's object layout and vtable
//             -ir         print the lowered intermediate representation
//             -bc         print the generated bytecode
//             -run        compile and run, returning the program's own result
//             -q          diagnostics only, no banner
//
//  With no file it reads DEFAULT_INPUT below: Xcode runs the binary from the
//  build products folder, so the default is an absolute path.  Pass a path via
//  Product > Scheme > Edit Scheme > Arguments to analyse a different file.
//
//  Exit status: 0 clean, 1 errors, 2 the file could not be read.
//
//  C++98 only.
//

#include <cstddef>
#include <cstdlib>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

#include "AST.h"
#include "AST1.h"
#include "Diagnostics.h"
#include "Bytecode.h"
#include "CodeGen.h"
#include "IR.h"
#include "Layout.h"
#include "Lower1.h"
#include "Parser.h"
#include "Parser1.h"
#include "Semantic.h"
#include "VM.h"

// Outside the Compiler++ source folder on purpose: that folder is a
// synchronized group, so any .cpp inside it would be compiled into the target.
static const char *DEFAULT_INPUT =
    "/Users/g.r.akhtar/Documents/Compiler++/point_input.cpp";

static bool readFile(const std::string &path, std::string &out) {
    std::ifstream in(path.c_str());
    if (!in) return false;
    std::ostringstream ss;
    ss << in.rdbuf();
    out = ss.str();
    return true;
}

// Diagnostics read better without the path.
static std::string baseName(const std::string &path) {
    const std::string::size_type slash = path.find_last_of('/');
    return (slash == std::string::npos) ? path : path.substr(slash + 1);
}

int main(int argc, char **argv) {
    bool showAst = false;
    bool showLayout = false;
    bool showIR = false;
    bool showBC = false;
    bool doRun = false;
    bool quiet = false;
    std::string path;

    for (int i = 1; i < argc; ++i) {
        const std::string arg = argv[i];
        if      (arg == "-ast")    showAst = true;
        else if (arg == "-layout") showLayout = true;
        else if (arg == "-ir")     showIR = true;
        else if (arg == "-bc")     showBC = true;
        else if (arg == "-run")    doRun = true;
        else if (arg == "-q")      quiet = true;
        else                       path = arg;
    }
    if (path.empty()) path = DEFAULT_INPUT;

    std::string source;
    if (!readFile(path, source)) {
        std::cerr << "Cannot open input file: " << path << std::endl;
        return 2;
    }

    Diagnostics diag(baseName(path));

    // parseTranslationUnit() is the C layer's, but every hook it calls is
    // virtual, so a cxx::Parser parses the C++ forms through the same loop.
    cxx::Parser parser(source, diag);
    std::vector<cc::Decl*> unit = parser.parseTranslationUnit();

    // Analysis runs even after syntax errors, and BEFORE printing: it writes
    // conclusions back into the tree (virtualness, overrides) that a dump taken
    // earlier would not show.
    {
        SemanticAnalyzer sem(diag);
        sem.analyze(unit);

        if (showAst) {
            if (!quiet) std::cout << "=== SYNTAX TREE: " << baseName(path) << " ===" << std::endl;
            for (std::size_t i = 0; i < unit.size(); ++i) unit[i]->print(0);
            std::cout << std::endl;
        }

        // Runs ALWAYS, not only when printing: it enforces constraints of its
        // own, and a diagnostic must not depend on a debug flag.
        Layout layout(diag);
        layout.computeAll(sem.classMap());
        if (showLayout) {
            if (!quiet) std::cout << "=== OBJECT LAYOUT: " << baseName(path) << " ===" << std::endl;
            layout.print();
        }

        // Only over a tree that survived analysis: lowering unresolved names
        // would produce nonsense rather than a better diagnostic.
        if ((showIR || showBC || doRun) && !diag.hadError()) {
            IRModule module;
            {
                cxx::Lowering lower(module, layout, diag, sem.classMap());
                lower.lowerClasses();
                lower.lowerUnit(unit);
            }
            if (showIR) {
                if (!quiet) std::cout << "=== IR: " << baseName(path) << " ===" << std::endl;
                module.print();
            }

            if ((showBC || doRun) && !diag.hadError()) {
                Image image;
                CodeGen gen(diag);
                gen.generate(module, image);

                if (showBC) {
                    if (!quiet) std::cout << "=== BYTECODE: " << baseName(path) << " ===" << std::endl;
                    image.disassemble();
                }
                if (doRun && !diag.hadError()) {
                    if (!quiet) std::cout << "=== RUN: " << baseName(path) << " ===" << std::endl;
                    VM vm;
                    bool ok = false;
                    const long result = vm.run(image, ok);
                    if (!ok) {
                        std::cout.flush();
                        std::cerr << baseName(path) << ": runtime error: "
                                  << vm.errorMessage() << std::endl;
                        for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
                        return 3;
                    }
                    std::cout.flush();
                    if (!quiet) {
                        std::cout << "main returned " << result
                                  << "  (" << vm.stepCount() << " steps)" << std::endl;
                    }
                    for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
                    return 0;
                }
            }
        }
    }

    if (!quiet) diag.printSummary();

    for (std::size_t i = 0; i < unit.size(); ++i) delete unit[i];
    return diag.hadError() ? 1 : 0;
}
